------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">✍ EJERCICIOS NUMPY PARA @EGGERS</h3><br>
------------------------------------------------------------------------------------------------------<br>

1. Crea un vector entre 7 y 66.
2. Invierte el vector generado anteriormente.
3. Matriz de 4x4 con valores entre 0 y 15.
5. Crea la matriz identidad de 5x5.
6. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.
7. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
8. Crea un array de ceros de 2x7.
9. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.
10. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

In [1]:
import numpy as np
# Crear un vector entre 7 y 66
vector = np.arange(7,67)
vector

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66])

In [2]:
# Invertir el vector generado anteriormente
vector_invertido = vector[::-1]
vector_invertido

array([66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7])

In [3]:
# Matriz 4x4 con valores entre 0 y 15
matriz = np.arange(0,16).reshape(4,4)
matriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
# Crea la matriz de identidad de 5x5
identidad = np.identity(5)
identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
# Crea una matriz de 5x5 donde la posición central y todas las posiciones que 
# conforman el marco valgan 1 y el resto 0
matriz2 = np.zeros((5,5))
matriz2[0,:] = 1
matriz2[4,:] = 1
matriz2[:,0] = 1
matriz2[:,4] = 1
matriz2[2,2] = 1
matriz2

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
matriz3 = np.array([[3,2,1,0], [3,2,1,0], [3,2,1,0], [3,2,1,0]])
matriz3

array([[3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0]])

In [8]:
# Crea un array de ceros de 2x7.
matriz4 = np.zeros(14).reshape(2,7)
matriz4

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
# Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1
matriz5 = np.zeros(20).reshape(5,4)
matriz5[0,:] = 1
matriz5

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
# Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.
# El array será de 8x8
ajedrez = np.zeros(64)
ajedrez

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
for index, value in np.ndenumerate(ajedrez):
    if index[0] % 2 == 0:
        ajedrez[index] = 1
ajedrez

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

In [100]:
ajedrezdef = ajedrez.reshape(8,8)
ajedrezdef

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [101]:
#for index, x in np.ndenumerate(ajedrezdef):
 #   if index[0] % 2 != 0:
        #print(index[0])
  #      ajedrezdef[index[0]] = ajedrezdef[index[0],::-1]       
# ajedrezdef
ajedrezdef[0] = ajedrezdef[0,::-1]
ajedrezdef[2] = ajedrezdef[2,::-1]
ajedrezdef[4] = ajedrezdef[4,::-1]
ajedrezdef[6] = ajedrezdef[6,::-1]
ajedrezdef

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])